### PR TITLE
Parserev

### PR DESCRIPTION
**Pull request by MrChico**
Our current parsing setup reversed all lists...
@xwvvvvwx I think this might also solve #38 ?

### CODE REVIEW

**Comment by xwvvvvwx** [comment]
> @xwvvvvwx I think this might also solve #38 ?

Yes it looks that why, but I don't really understand why?

**Comment by MrChico** [comment]
I think things might have just been out of place there

**Comment by xwvvvvwx** [comment]
wdym out of place?

**Comment by MrChico** [comment]
I think things might have been correct, we were just looking in the wrong place because everything was reversed. So the "first case" was actually the last

**Comment by xwvvvvwx** [comment]
hmmmm no I don't think that was the case, if you look here: https://github.com/ethereum/act/blob/b91cb38438cccd713eb985a6222bee1c83a502f4/tests/token/transfer.act.typed.json#L3 the `stateUpdates` block is for the `transferFrom` `Pass` spec and contains only `Left` values.

**Comment by MrChico** [comment]
yes, but the last case of `transferFrom` also contains no state updates:
```
case src == dst:

     balanceOf[CALLER]
     allowance[src][CALLER]
     balanceOf[src]
     balanceOf[dst]

```

**Comment by xwvvvvwx** [comment]
ohhhhhhhhhhh yes.

**Pull request merged**
